try{
alert("hi everyone");
alert(x);

}
catch(er){
    console.log("insert catch block");
    console.log(err);
    // console.log(err.name);
    // console.log(err.message);

}finally{
    alert("Bye everyone");
}